### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by H-Yulong** [VictorZXY/cst-part-ii-types-cheat-sheet#1]
Typo in the introduction rule of STLC's binary product:

\Gamma |- e1 : T1    \Gamma |- e2 : T2
------------------------------------------- xI
         \Gamma |- <e1, e2> : 1

It should be

\Gamma |- e1 : T1    \Gamma |- e2 : T2
------------------------------------------- xI
         \Gamma |- <e1, e2> : T1 x T2

instead.

**Comment by VictorZXY** [comment]
Hi Yulong,

Thanks for detecting the typo! It has now been fixed.

Best,
Victor
